name: Deploy Recommend System

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

env:
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  AWS_REGION: ap-northeast-1

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.14"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

    - name: Download .env file
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
          command: cp
          source: s3://${{ env.S3_BUCKET_NAME }}/env-files/.env
          destination: ./.env
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}

    - name: Verify .env file
      run: |
        echo "Checking .env file..."
        cat .env

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version tag
      id: version
      run: |
        # Create a unique version tag using the short commit SHA
        echo "VERSION_TAG=$(date +%Y%m%d%H%M)-${{ github.sha::0:8 }}" >> $GITHUB_ENV

    - name: Build and tag Docker image
      run: |
        # Build the Docker image with both the 'latest' and unique tags
        docker build . \
          --file Dockerfile \
          --tag ${{ secrets.DOCKER_USERNAME }}/recommend-system:latest \
          --tag ${{ secrets.DOCKER_USERNAME }}/recommend-system:${{ env.VERSION_TAG }}

        # Push both tags to Docker Hub
        docker push ${{ secrets.DOCKER_USERNAME }}/recommend-system:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/recommend-system:${{ env.VERSION_TAG }}
